services:
  tmdb-service:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: tmdb-service:latest
    hostname: tmdb-service.mediamaster.internal
    container_name: tmdb-service.mediamaster.internal
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - mediamaster-internal-network

networks:
  mediamaster-internal-network:
    name: mediamaster-internal-network
